### ISSUE TITLE
Consider having -k as the default behavior

### ISSUE THREAD

**Issue by aimxhaisse** [moul/scaleway-cli#5]
Currently:

```
scw exec $uuid 'ls -l'
```
Prompts to add the SSH key to known hosts (we need to add -k to bypass this check).

Since the usage of this command is primarily for scripting, it would be cool to have -k as the default behavior, and introduce a --safe (or equivalent) extra argument to force the check.

**Comment by moul** [comment]
:+1:

I will:
- [ ] switch to `-k` behaviour by default
- [ ] add a `--safe` argument
- [ ] add a environment variable
- [ ] update `README.md`

**Comment by aimxhaisse** [comment]
:ok_hand:
